# Generated by Django 2.2.5 on 2019-10-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0002_auto_20190929_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputfile',
            old_name='upload_files',
            new_name='files',
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('DONE', 'DONE')], default='NEW', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(to='nano.Files')),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nano.InputFile')),
            ],
            options={
                'verbose_name': 'qc',
                'verbose_name_plural': 'qc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('DONE', 'DONE')], default='NEW', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(to='nano.Files')),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nano.QC')),
            ],
            options={
                'verbose_name': 'GroupComparison',
                'verbose_name_plural': 'GroupComparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeVolcano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('DONE', 'DONE')], default='NEW', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(to='nano.Files')),
                ('group_comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nano.GroupComparison')),
            ],
            options={
                'verbose_name': 'GroupComparison',
                'verbose_name_plural': 'GroupComparisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
