# Generated by Django 2.2.5 on 2019-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0003_auto_20191006_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='uploads/qc/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='qc',
            name='files',
        ),
        migrations.AlterField(
            model_name='files',
            name='upload_file',
            field=models.FileField(upload_to='uploads/input_file/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='qc',
            name='qc_files',
            field=models.ManyToManyField(to='nano.QCFiles'),
        ),
    ]
