# Generated by Django 2.2.5 on 2019-11-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0005_auto_20191006_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gevolcano',
            options={'ordering': ['-created_at'], 'verbose_name': 'GeVolcano', 'verbose_name_plural': '4 - GeVolcanos'},
        ),
        migrations.AlterModelOptions(
            name='groupcomparison',
            options={'ordering': ['-created_at'], 'verbose_name': 'GroupComparison', 'verbose_name_plural': '3 - GroupComparisons'},
        ),
        migrations.AlterModelOptions(
            name='inputfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'input_file', 'verbose_name_plural': '1 - input_files'},
        ),
        migrations.AlterModelOptions(
            name='qc',
            options={'ordering': ['-created_at'], 'verbose_name': 'qc', 'verbose_name_plural': '2 - qc'},
        ),
        migrations.AddField(
            model_name='inputfile',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('DONE', 'DONE')], default='NEW', max_length=4),
        ),
    ]
