# Generated by Django 2.2.5 on 2019-11-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nano', '0006_auto_20191102_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc',
            name='quality_control',
            field=models.FileField(default='', upload_to='uploads/qc/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
